optimistic:
	g++ -o optimistic optimistic.cpp -lpthread -g
	time ./optimistic

fine:
	g++ -o fine_grained fine_grained.cpp -lpthread -g
	time ./fine_grained

coarse:
	g++ -o coarse_grained coarse_grained.cpp -lpthread
	time ./coarse_grained
